import ReduxProvider from "@/redux/provider";
import { Inter } from "next/font/google";
import Script from "next/script";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
// import useTheme from "@/hooks/useTheme"

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   deScription: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // useTheme();
  return (
    <html>
      <head>
        <title>Cryptech | Bitcoin And Crypto Currency </title>

        <title>Cryptech | Bitcoin And Crypto Currency </title>
      </head>
      <body>
        <ReduxProvider>{children}</ReduxProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
