"use client";
import React, { createContext, useContext, useState, useEffect } from "react";
import ReduxProvider from "@/redux/provider";
import { Inter } from "next/font/google";
import Script from "next/script";
// import useTheme from "@/hooks/useTheme";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   deScription: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  //   useTheme();
  return (
    <html dir="ltr" lang="en" data-bs-theme="dark">
      <body>
        <script>0</script>
        {children}
        {/* <ReduxProvider>{children}</ReduxProvider> */}
      </body>
    </html>
  );
}
